#
# Copyright 2021-2023 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

replicaCount: 1

image:
  # Check https://hub.docker.com/u/softwareradiosystems for available images
  repository: ninjab3s/srsran-5g-gnb
  pullPolicy: IfNotPresent
  tag: "srskit"

imagePullSecrets:
  - name: regcred

nameOverride: "srsran-project-cudu"
fullnameOverride: "srsran-project-cudu-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-gnb"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

network:
  hostNetwork: true

resources: {}
  # limits:
  #   cpu: 12
  #   memory: 16Gi
  #   hugepages-1Gi: 2Gi
  # requests:
  #   cpu: 12
  #   memory: 16Gi
  #   hugepages-1Gi: 2Gi

nodeSelector: {}
  # kubernetes.io/hostname: node1

tolerations: {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}

debugging:
  enabled: true
  storageCapacity: "100Mi"
  hostPath: "/mnt/debugging-logs"
  containerPath: "/tmp"

config:
  amf:
    hostname: open5gs-amf-ngap.open5gs                                     # The address or hostname of the AMF.
    bind_interface: eth0                                                   # A local IP that the gNB binds to for traffic from the AMF.

  slicing:
  - sst: 1
    sd: 000001
  - sst: 2
    sd: 000001
  - sst: 3
    sd: 000001

  ru_ofh:
    ru_bandwidth_MHz: 100                                           # RU instantaneous bandwidth.
    t1a_max_cp_dl: 500                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
    t1a_min_cp_dl: 250                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
    t1a_max_cp_ul: 465                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
    t1a_min_cp_ul: 250                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
    t1a_max_up: 250                                                 # Maximum T1a on User-Plane in microseconds.
    t1a_min_up: 80                                                  # Minimum T1a on User-Plane in microseconds.
    ta4_max: 500                                                    # Maximum Ta4 on User-Plane in microseconds.
    ta4_min: 25                                                     # Minimum Ta4 on User-Plane in microseconds.
    is_prach_cp_enabled: true                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
    ignore_ecpri_payload_size: true                                 # Configures if eCPRI payload size field should be ignored by the eCPRI packet decoder.
    compr_method_ul: bfp                                            # Uplink compression method.
    compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
    compr_method_dl: bfp                                            # Downlink compression method.
    compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
    compr_method_prach: bfp                                         # PRACH compression method.
    compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
    enable_ul_static_compr_hdr: false                                # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
    enable_dl_static_compr_hdr: false                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
    iq_scaling: 4.0                                                # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
    cells:
    - network_interface: enp152s0f0                                 # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 6c:ad:ad:00:0a:8e                              # RU MAC address.
      du_mac_addr: 00:11:22:33:66:55                              # DU MAC address.
      vlan_tag_cp: 163                                              # VLAN tag value for C-Plane.
      vlan_tag_up: 164                                              # VLAN tag value for U-Plane.
      prach_port_id: [4, 5, 6, 7]                                          # PRACH eAxC port value.
      dl_port_id: [0, 1, 2, 3]                                          # Downlink eAxC port values.
      ul_port_id: [0, 1, 2, 3]                                          # Uplink eAxC port values.

  cell_cfg:
    dl_arfcn: 640000                                                # ARFCN of the downlink carrier (center frequency).
    band: 78                                                        # The NR band.
    channel_bandwidth_MHz: 100                                      # Bandwith in MHz. Number of PRBs will be automatically derived.
    common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
    plmn: "72470"                                                   # PLMN broadcasted by the gNB.
    tac: 1                                                          # Tracking area code (needs to match the core configuration).
    pci: 1                                                          # Physical cell ID.
    nof_antennas_dl: 4                                              # Downlink number of antennas.
    nof_antennas_ul: 2                                              # Uplink number of anntennas.
    prach:
      prach_config_index: 159                                         # PRACH configuration index.
      prach_root_sequence_index: 1                                  # PRACH root sequence index.
      zero_correlation_zone: 0                                      # Zero correlation zone.
      prach_frequency_start: 12                                      # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.
    pdsch:
      mcs_table: qam256

  log:                                                              # Set debugging->enabled->true in order to make logs persistent. Make sure hostPath and log file path match.
    filename: /tmp/gnb.log                                          # Path of the log file.
    all_level: warning                                              # Logging level applied to all layers.

  pcap:
    mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
    mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
    ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
    ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.

  metrics:
    autostart_stdout_metrics: true   # Enable reporting metrics in stdout
    rlc_json_enable: true              # Enable RLC metrics reporting (need to deliver measurements to E2SM_KPM service model)
    rlc_report_period: 1000            # Set reporting period to 1s
    # enable_json_metrics: true        # Enable reporting metrics in JSON format
    # addr: 10.233.43.143              # Metrics-server IP
    # port: 55555                      # Metrics-server Port

  e2:
    enable_du_e2: false                # Enable DU E2 agent (one for each DU instance)
    e2sm_kpm_enabled: false            # Enable KPM service module
    e2sm_rc_enabled: false             # Enable KPM service module 
    hostname: service-ricplt-e2term-sctp-alpha.ricplt # RIC Service (on K8s) or IP address
    bind_interface: eth0 # A local IP that the E2 agent binds to traffic from the RIC. ONLY required if running the RIC on a separate machine.
    port: 36421 # RIC SCTP port
