#
# Copyright 2021-2023 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

replicaCount: 1

image:
  # Check https://hub.docker.com/u/softwareradiosystems for available images
  repository: muriloavlis/srsran-5g
  pullPolicy: IfNotPresent
  tag: "zmq_latest"

imagePullSecrets:
  - name: regcred

nameOverride: "srsran-gnb-zmq"
fullnameOverride: "srsran-gnb-zmq-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-gnb"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

network:
  hostNetwork: true

resources:
  {}
  # limits:
  #   cpu: 12
  #   memory: 16Gi
  #   hugepages-1Gi: 2Gi
  # requests:
  #   cpu: 12
  #   memory: 16Gi
  #   hugepages-1Gi: 2Gi

nodeSelector:
  {}
  # kubernetes.io/hostname: node1

tolerations:
  {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}

debugging:
  enabled: true
  storageCapacity: "100Mi"
  hostPath: "/mnt/debugging-logs"
  containerPath: "/tmp"

config:
  amf:
    addr: 10.233.3.84 # The address or hostname of the AMF.
    bind_addr: 127.0.0.1 # A local IP that the gNB binds to for traffic from the AMF.

  ru_sdr:
    device_driver: zmq
    device_args: tx_port=tcp://*:2000,rx_port=tcp://0.0.0.0:2001,id=srs_gnb,base_srate=23.04e6
    srate: 23.04
    tx_gain: 75
    rx_gain: 75

  slicing:
    - sst: 1
      sd: 1

  cell_cfg:
    dl_arfcn: 368500 # ARFCN of the downlink carrier (center frequency).
    band: 3 # The NR band.
    channel_bandwidth_MHz: 20 # Bandwith in MHz. Number of PRBs will be automatically derived.
    common_scs: 15 # Subcarrier spacing in kHz used for data.
    plmn: "72470" # PLMN broadcasted by the gNB.
    tac: 1 # Tracking area code (needs to match the core configuration).
    pci: 1 # Physical cell ID.
    nof_antennas_dl: 1 # Optional UINT (1). Sets the number of antennas for downlink transmission. Supported: [1 for emulated].
    nof_antennas_ul: 1 # Optional UINT (1). Sets the number of antennas for uplink transmission. Supported: [1 for emulated].

  e2:
    enable_du_e2: false # Enable DU E2 agent (one for each DU instance)
    e2sm_kpm_enabled: true # Enable KPM service module
    e2sm_rc_enabled: true # Enable KPM service module
    addr: 192.168.0.1 # RIC IP address
    bind_addr: 192.168.0.10 # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine.
    port: 36422 # RIC port

  log: # Set debugging->enabled->true in order to make logs persistent. Make sure hostPath and log file path match.
    filename: /tmp/gnb.log # Path of the log file.
    all_level: debug # Logging level applied to all layers.

  pcap:
    mac_enable: false # Set to true to enable MAC-layer PCAPs.
    mac_filename: /tmp/gnb_mac.pcap # Path where the MAC PCAP is stored.
    ngap_enable: false # Set to true to enable NGAP PCAPs.
    ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
    e2ap_enable: true # Set to true to enable E2AP PCAPs.
    e2ap_filename: /tmp/gnb_e2ap.pcap # Path where the E2AP PCAP is stored.

  metrics:
    autostart_stdout_metrics: true # Enable reporting metrics in stdout
    # enable_json_metrics: true        # Enable reporting metrics in JSON format
    # addr: 10.233.43.143              # Metrics-server IP
    # port: 55555                      # Metrics-server Port
