#
# Copyright 2021-2023 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

replicaCount: 1

image:
  # Check https://hub.docker.com/u/softwareradiosystems for available images
  repository: muriloavlis/srsran-5g
  pullPolicy: Always
  tag: "split72_latest"

imagePullSecrets:
  - name: regcred

nameOverride: "srsran-gnb"
fullnameOverride: "srsran-gnb"

serviceAccount:
  create: true
  annotations: {}
  name: "srsadmin-gnb"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add: ["SYS_NICE", "NET_ADMIN"]
  privileged: true
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

network:
  hostNetwork: true

resources:
  {}
  # limits:
  #   cpu: 12
  #   memory: 16Gi
  #   hugepages-1Gi: 2Gi
  # requests:
  #   cpu: 12
  #   memory: 16Gi
  #   hugepages-1Gi: 2Gi

nodeSelector:
  kubernetes.io/hostname: oran-cloud2

tolerations:
  {}
  # - key: "purpose"
  #   value: "manual-testing"
  #   operator: "Equal"
  #   effect: "NoSchedule"

affinity: {}

debugging:
  enabled: true
  storageCapacity: "100Mi"
  hostPath: "/mnt/debugging-logs"
  containerPath: "/tmp"

config:
  gnb_id: 0 # Optional UINT (411). Sets the numerical ID associated with the gNB.
  gnb_id_bit_length: 32 # Optional UNIT. Sets the bit length of the gnb_id above. Format: integer between [22 - 32]
  ran_node_name: srs_gnb_01 # Optional TEXT (srsgnb01). Sets the text ID associated with the gNB. Format: string without spaces.
  gnb_du_id: 0 # Optional UINT (0). Sets the gNB DU ID. Supported: [0 - 68719476735].

  amf:
    addr: 10.21.0.2 # The address or hostname of the AMF.
    bind_addr: acesso # A local IP that the gNB binds to for traffic from the AMF.
    port: 38412
    # no_core: true

  disable_ru_ofh: false

  slicing:
    - sst: 1
      sd: 0x000001
    - sst: 2
      sd: 0x000001
    - sst: 3
      sd: 0x000001

  ru_ofh:
    t1a_max_cp_dl: 420
    t1a_min_cp_dl: 250
    t1a_max_cp_ul: 420
    t1a_min_cp_ul: 250
    t1a_max_up: 196
    t1a_min_up: 80
    ta4_max: 500
    ta4_min: 25
    is_prach_cp_enabled: true
    ignore_ecpri_payload_size: true
    compr_method_ul: bfp
    compr_bitwidth_ul: 9
    compr_method_dl: bfp
    compr_bitwidth_dl: 9
    compr_method_prach: bfp
    compr_bitwidth_prach: 9
    enable_ul_static_compr_hdr: false
    enable_dl_static_compr_hdr: false
    iq_scaling: 1.0
    cells:
      - network_interface: xxxx # Ethernet interface name used to communicate with the RU.
        ru_mac_addr: 6c:ad:ad:xx:xx:xx # RU MAC address.
        du_mac_addr: 80:61:5f:xx:xx:xx # DU MAC address.
        vlan_tag_cp: 2 # VLAN tag value for CP.
        vlan_tag_up: 2 # VLAN tag value for UP.
        prach_port_id: [4, 5, 6, 7] # PRACH eAxC port values.
        dl_port_id: [0, 1] # Downlink eAxC port values.
        ul_port_id: [0, 1, 2, 3] # Uplink eAxC port values.

  cell_cfg:
    dl_arfcn: 640000 # ARFCN of the downlink carrier (center frequency).
    band: 78 # The NR band.
    channel_bandwidth_MHz: 100 # Bandwith in MHz. Number of PRBs will be automatically derived.
    common_scs: 30 # Subcarrier spacing in kHz used for data.
    plmn: "00101" # PLMN broadcasted by the gNB.
    tac: 7 # Tracking area code (needs to match the core configuration).
    pci: 1
    nof_antennas_dl: 4
    nof_antennas_ul: 1
    prach:
      prach_config_index: 159
      prach_root_sequence_index: 1
      zero_correlation_zone: 0
      prach_frequency_start: 12
    pdsch:
      mcs_table: qam256
    tdd_ul_dl_cfg:
      dl_ul_tx_period: 10
      nof_dl_slots: 7
      nof_dl_symbols: 6
      nof_ul_slots: 2
      nof_ul_symbols: 0

  e2:
    enable_du_e2: false # Enable DU E2 agent (one for each DU instance)
    e2sm_kpm_enabled: true # Enable KPM service module
    e2sm_rc_enabled: true # Enable KPM service module
    addr: 192.168.0.1 # RIC IP address or k8s service name
    bind_addr: lo # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine.
    port: 36421 # RIC port

  log: # Set debugging->enabled->true in order to make logs persistent. Make sure hostPath and log file path match.
    filename: /tmp/gnb.log # Path of the log file.
    all_level: debug # Logging level applied to all layers.

  pcap:
    mac_enable: false # Set to true to enable MAC-layer PCAPs.
    mac_filename: /tmp/gnb_mac.pcap # Path where the MAC PCAP is stored.
    ngap_enable: false # Set to true to enable NGAP PCAPs.
    ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
    e2ap_enable: true # Set to true to enable E2AP PCAPs.
    e2ap_filename: /tmp/gnb_e2ap.pcap # Path where the E2AP PCAP is stored.

  metrics:
    autostart_stdout_metrics: true # Enable reporting metrics in stdout
    stdout_metrics_period: 1000 # Sets the DU statistics report period in milliseconds. This metrics sets the console output period.
    rlc_json_enable: true # Enable RLC metrics reporting (need to deliver measurements to E2SM_KPM service model)
    rlc_report_period: 1000 # Set reporting period to 1s
    # enable_json_metrics: true        # Enable reporting metrics in JSON format
    # addr: 10.233.43.143              # Metrics-server IP
    # port: 55555                      # Metrics-server Port
