apiVersion: v1
kind: Service
metadata:
  name: srsgnb-gtpu
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: gtpu
      port: 2152
      protocol: UDP
      targetPort: gtpu
  publishNotReadyAddresses: true
  selector: {{- include "srsran-cudu.selectorLabels" . | nindent 6 }}