#
# Copyright 2021-2023 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "srsran-cudu.fullname" . }}
  labels:
    {{- include "srsran-cudu.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "srsran-cudu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "srsran-cudu.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "srsran-cudu.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.network.hostNetwork }}
      hostNetwork: true
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: srsgnb-configmap
            defaultMode: 0777
        {{- if .Values.debugging.enabled }}
        - name: srs-host-volume
          hostPath:
            path: {{ .Values.debugging.hostPath }}/{{ now | date "2006-01-02--15:04:05" }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if .Values.config.hal }}
        - name: hugepage-1gi
          emptyDir:
            medium: HugePages-1Gi
        {{- end }}
        {{- if .Values.srsue }}
        - name: srsue-config
          configMap:
            name: srsue-configmap
        {{- end }}
      containers:
        - name: {{ .Values.nameOverride }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: [ "/entrypoint.sh" ]
          args: [ "gnb" ]
          env:
            - name: AMF_HOST
              value: {{ .Values.config.amf.addr }}
            - name: AMF_BIND_INTERFACE
              value: {{ .Values.config.amf.bind_addr }}
            - name: RIC_HOST
              value: {{ .Values.config.e2.addr }}
            - name: RIC_BIND_INTERFACE
              value: {{ .Values.config.e2.bind_addr }}
          volumeMounts:
            - name: config-volume
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
            - name: config-volume
              mountPath: /etc/config/gnb-template.yml
              subPath: gnb-template.yml
            {{- if .Values.debugging.enabled }}
            - mountPath: {{ .Values.debugging.containerPath }}
              name: srs-host-volume
            {{- end }}
            {{- if .Values.config.hal }}
            - name: hugepage-1gi
              mountPath: /hugepages-1Gi
            {{- end }}
        {{- if .Values.srsue }}    
        - name: {{ .Values.srsue.name }}
          image: "{{ .Values.srsue.image.repository }}:{{ .Values.srsue.image.tag }}"
          imagePullPolicy: {{ .Values.srsue.image.pullPolicy | quote }}
          command: [ "srsue" ]
          args: [ "/etc/srsue/ue.conf" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: CONFIG_PATH
              value: /etc/srsue/ue.conf
          volumeMounts:
            - name: srsue-config
              mountPath: /etc/srsue/ue.conf
              subPath: ue.conf
        {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
