apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf-ngap-np
  namespace: open5gs
spec:
  selector:
    app.kubernetes.io/name: amf
  type: NodePort
  ports:
    - port: 38412
      targetPort: 38412
      nodePort: 30412
      protocol: SCTP
